version: "2.0"
services:
  openqa-trigger:
    build:
      dockerfile: Dockerfile
      context: openqa-trigger
    restart: always
    environment:
      - RUN_EVERY=600
    volumes:
      - ./openqa-trigger:/home/frontend/openqa-trigger
  openqa-mail-notification:
    build:
      dockerfile: Dockerfile
      context: openqa-mail-notification
    env_file:
      - openqa-mail-notification/.env
    restart: always
    volumes:
      - ./openqa-mail-notification:/home/frontend/openqa-mail-notification
  obs-package-status:
    build:
      dockerfile: Dockerfile
      context: obs-package-status
    restart: always
    environment:
      - RUN_EVERY=600
    volumes:
      - ./obs-package-status:/home/frontend/obs-package-status
