version: "2.0"
services:
  openqa-trigger:
    build:
      dockerfile: Dockerfile
      context: openqa-trigger
    restart: always
    env_file:
      - openqa-trigger/.env
    volumes:
      - ./openqa-trigger:/home/frontend/openqa-trigger
  openqa-mail-notification:
    build:
      dockerfile: Dockerfile
      context: openqa-mail-notification
    env_file:
      - openqa-mail-notification/.env
    restart: always
    volumes:
      - ./openqa-mail-notification:/home/frontend/openqa-mail-notification
  obs-package-status:
    build:
      dockerfile: Dockerfile
      context: obs-package-status
    env_file:
      - obs-package-status/.env
    restart: always
    volumes:
      - ./obs-package-status:/home/frontend/obs-package-status
